# Generated by Django 4.2.1 on 2023-06-16 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenshipCard',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=100)),
                ('dob', models.DateField()),
                ('birth_district', models.CharField(choices=[('kathmandu', 'Kathmandu'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur')], max_length=100)),
                ('birth_municipality', models.CharField(choices=[('kamp', 'Kathmandu Metropolitian City'), ('lamp', 'Lalitpur Metropolitian City'), ('bhmp', 'Bhaktapur Metropolitian City')], max_length=100)),
                ('birth_place_ward', models.IntegerField()),
                ('permanent_address_district', models.CharField(choices=[('kathmandu', 'Kathmandu'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur')], max_length=100)),
                ('permanent_address_metropolitian', models.CharField(choices=[('kathmandu', 'Kathmandu'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur')], max_length=100)),
                ('permanent_address_ward', models.IntegerField()),
                ('issued_date', models.DateField()),
                ('issued_from', models.CharField(choices=[('kathmandu', 'Kathmandu'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur')], max_length=300)),
                ('fathers_name', models.CharField(max_length=500)),
                ('mothers_name', models.CharField(max_length=500)),
                ('spouse_name', models.CharField(blank=True, default=None, max_length=500)),
                ('mobile_no', models.BigIntegerField(unique=True)),
                ('citizen_img', models.ImageField(default='', upload_to='citizen')),
                ('cid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('citizenship_type', models.CharField(choices=[('descent', 'Descent'), ('birth', 'Birth'), ('honorary', 'Honorary'), ('naturalized', 'Naturalized')], max_length=100)),
            ],
            options={
                'ordering': ['cid'],
            },
        ),
        migrations.CreateModel(
            name='SingleVRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vrsId', models.UUIDField(blank=True, unique=True)),
                ('vrs_applicant_of', models.CharField(max_length=200)),
                ('vrs_nature', models.CharField(max_length=200)),
                ('vrs_type', models.CharField(max_length=200)),
                ('vrs_old_owner', models.BigIntegerField(blank=True, null=True)),
                ('vrs_cit_id', models.BigIntegerField()),
                ('vrs_office_province', models.CharField(max_length=200)),
                ('vrs_office', models.CharField(max_length=200)),
                ('vrs_ins_policy_num', models.IntegerField(blank=True, null=True)),
                ('vrs_ins_pan_num', models.IntegerField(blank=True, null=True)),
                ('vrs_ins_company', models.IntegerField(blank=True, null=True)),
                ('vrs_ins_company_addr', models.CharField(blank=True, max_length=500, null=True)),
                ('vrs_ins_validity_start', models.DateField(blank=True, null=True)),
                ('vrs_ins_validity_end', models.DateField(blank=True, null=True)),
                ('vrs_engine_type', models.CharField(max_length=100)),
                ('vrs_mfg_year', models.CharField(max_length=100)),
                ('vrs_vehicle_cat', models.CharField(max_length=100)),
                ('vrs_vehicle_class', models.CharField(max_length=100)),
                ('vrs_engine_no', models.IntegerField()),
                ('vrs_engine_power', models.IntegerField()),
                ('vrs_chasis_no', models.IntegerField()),
                ('vrs_vehicle_model', models.CharField(max_length=200)),
                ('vrs_vehicle_mfc', models.CharField(max_length=200)),
                ('vrs_cylinder_no', models.IntegerField()),
                ('vrs_seat_capacity', models.IntegerField()),
                ('vrs_vehicle_color', models.CharField(max_length=200)),
                ('vrs_vehicle_wt', models.FloatField()),
                ('vrs_custom_clearance_date', models.DateField()),
                ('vrs_custom_declaration_no', models.BigIntegerField()),
                ('vrs_custom_office', models.CharField(max_length=200)),
                ('vrs_custom_payment', models.CharField(max_length=100)),
                ('vrs_custom_payment_amt', models.FloatField()),
                ('vrs_applicant_province', models.CharField(blank=True, max_length=100, null=True)),
                ('vrs_applicant_district', models.CharField(blank=True, max_length=100, null=True)),
                ('vrs_applicant_local', models.CharField(blank=True, max_length=300, null=True)),
                ('vrs_applicant_ward', models.IntegerField(blank=True, null=True)),
                ('vrs_applicant_phone', models.BigIntegerField(blank=True, null=True)),
                ('citizen_doc_img', models.ImageField(upload_to='vrs-single/citizenship-card/')),
                ('engine_img', models.ImageField(upload_to='vrs-single/engine/')),
                ('chasis_img', models.ImageField(upload_to='vrs-single/chasis/')),
                ('custom_related_img', models.ImageField(upload_to='vrs-single/custom/')),
                ('vehicle_img', models.ImageField(upload_to='vrs-single/vehicle/')),
                ('bill_img', models.ImageField(upload_to='vrs-single/bill/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Verify Pending'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='submitted', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vrs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NationalIdentityCard',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nin', models.BigIntegerField(primary_key=True, serialize=False)),
                ('contact', models.IntegerField(unique=True)),
                ('citizen_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle_registration_api.citizenshipcard')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nin'],
            },
        ),
    ]
