# Generated by Django 4.2.1 on 2023-06-18 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle_registration_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlevrs',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Verify Pending'), ('rejected', 'Rejected'), ('verified', 'Verified'), ('registered', 'Registered')], default='submitted', max_length=100),
        ),
        migrations.CreateModel(
            name='SingleVRS_Extended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('comments', models.TextField()),
                ('vrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_vrs_extended', to='vehicle_registration_api.singlevrs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KhaltiTransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idx', models.CharField(max_length=500, unique=True)),
                ('amount', models.FloatField()),
                ('transaction_details', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='khalti_transaction_vrs_user', to=settings.AUTH_USER_MODEL)),
                ('vrs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='khalti_transaction_vrs', to='vehicle_registration_api.singlevrs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
