# Generated by Django 4.2.1 on 2023-06-18 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_registration_api', '0002_alter_singlevrs_status_singlevrs_extended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlevrs_extended',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singlevrs_extended',
            name='vrs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vrs_xtd', to='vehicle_registration_api.singlevrs'),
        ),
    ]
