# Generated by Django 4.2.1 on 2023-06-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_registration_api', '0003_alter_singlevrs_extended_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenshipcard',
            name='cid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='singlevrs',
            name='vrs_cit_id',
            field=models.CharField(max_length=100),
        ),
    ]
