# Generated by Django 4.2.1 on 2023-06-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_registration_api', '0004_alter_citizenshipcard_cid_alter_singlevrs_vrs_cit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenshipcard',
            name='mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
